apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: microservices-demo
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP