apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microservices-demo
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: NodePort