name: Frontend CI/CD

on:
  push:
    paths:
      - 'services/frontend/**'
      - '.github/workflows/frontend-ci.yml'
    branches:
      - main
      - staging
  pull_request:
    paths:
      - 'services/frontend/**'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/frontend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd services/frontend
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd services/frontend
          pytest
  
  build-and-push:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/frontend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}-latest
      
      - name: Update Kubernetes manifests
        run: |
          # Determine the environment based on branch
          ENVIRONMENT="${{ steps.extract_branch.outputs.branch }}"
          if [ "$ENVIRONMENT" = "main" ]; then
            ENVIRONMENT="production"
          fi
          
          # Update the image tag in the deployment file
          sed -i "s|image: .*frontend.*|image: ${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}|" ./k8s/frontend/deployment.yaml
          
          # Commit and push the changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./k8s/frontend/deployment.yaml
          git commit -m "Update frontend deployment with image ${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}"
          git push